model:
  name: SNR
  in_channels: 3
  base_channels: 64
  encoder_blocks: 5
  decoder_blocks: 10
  res_blocks: 6
  dim: 1600
  num_layers: 6
  num_heads: 8
  lambda_vgg: 0.02


train:
  epochs: 4000
  lr: 0.0004
  optimizer:
    name: Adam
    weight_decay: 0.0
    betas: [0.9, 0.99]
  scheduler:
    name: MultiStepLR
    gamma: 0.5
    milestones: [350, 700, 1400, 2100]
  log_dir: ./logs/snr/lolv1


data:
  name: LOLv1
  root: /home/nju-student/mkh/datasets/LLIE/LOLv1
  batch_size: 8
  num_workers: 4
  pin_memory: True
  height: 400
  width: 600
  val_ratio: 0.2
  seed: 42
