model:
  name: DiffLL
  diffusion_timesteps: 200
  sampling_timesteps: 10
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  in_channels: 3
  mid_channels: 64
  out_channels: 3
  channels_ratio: [ 1, 2, 3, 4 ]
  num_blocks: 2
  resample_with_conv: True
  dropout: 0.0

train:
  epochs: 500
  lr: 0.0001
  optimizer:
    name: Adam
    weight_decay: 0
  scheduler:
    name: StepLR
    step_size: 50
    gamma: 0.8
  log_dir: ./logs/diff_ll/lolv1
  use_ema: True
  ema_decay: 0.999


data:
  name: LOLv1
  root: /home/nju-student/mkh/datasets/LLIE/LOLv1
  batch_size: 8
  num_workers: 4
  pin_memory: True
  height: 400
  width: 600
  crop_size: 256
  val_ratio: 0.2
  seed: 230
