model:
  name: LLFlow
  ConditionalEncoder:
    in_channels: 12
    num_blocks: 24
    num_features: 64
    base_channels: 32
    num_layers: 5
    blocks: [1, 3, 5, 7]
  FlowUpsampler:
    in_channels: 3
    num_steps: 12
    additional_steps: 2
    num_blocks: 3
    actnorm_scale: 1.0


train:
  epochs: 1000
  lr: 0.000005
  betas: [0.9, 0.99]
  optimizer:
    name: Adam
    weight_decay: 0
  scheduler:
    name: MultiStepLRWarmup
    milestones: [43000, 64600, 77500, 82000]
    gamma: 0.5
    warmup_steps: 8000
  log_dir: ./logs/ll_flow/lolv2_real
  gt_ratio: 0.2


data:
  name: LOLv2_Real
  flow: True
  root: /home/nju-student/mkh/datasets/LLIE/LOLv2/Real_captured
  batch_size: 8
  num_workers: 4
  pin_memory: True
  height: 400
  width: 600
  crop_size: 160
  val_ratio: 0.2
  seed: 10
  quant: 32
